name: Generate 5g.json

on:
  push:
    paths:
      - "public/images/5g/**"
      - "scripts/generate-5g-json.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run generator script
        run: npm run generate:5g

      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/5g.json
          git commit -m "chore: auto-update 5g.json" || echo "No changes to commit"
          git push
